import "server-only";

export type AgentToolContext = {
  prompt: string;
  plan: {
    title: string;
    summary: string;
  };
  webhookUrl?: string;
  topic?: string;
  items?: NewsItem[];
  discordPayload?: unknown;
};

export type AgentToolResult = {
  tool: string;
  status: "completed" | "skipped";
  message: string;
  output?: Record<string, unknown>;
};

export type NewsItem = {
  title: string;
  url: string;
  source: string;
};

type AgentTool = {
  name: string;
  description: string;
  execute: (context: AgentToolContext) => Promise<AgentToolResult>;
};

const MAX_NEWS_ITEMS = 5;

function getTopicFromPrompt(prompt: string) {
  const normalized = prompt.toLowerCase();
  if (normalized.includes("ai")) return "AI technology";
  if (normalized.includes("finance") || normalized.includes("market")) {
    return "finance markets";
  }
  if (normalized.includes("security")) return "cybersecurity";
  if (normalized.includes("startup")) return "startups";
  return "technology";
}

function normalizeNewsItem(raw: unknown): NewsItem | null {
  if (!raw || typeof raw !== "object") return null;
  const item = raw as {
    title?: unknown;
    story_title?: unknown;
    url?: unknown;
    story_url?: unknown;
    author?: unknown;
  };
  const title =
    typeof item.title === "string" && item.title.trim()
      ? item.title.trim()
      : typeof item.story_title === "string"
        ? item.story_title.trim()
        : "";
  const url =
    typeof item.url === "string" && item.url.trim()
      ? item.url.trim()
      : typeof item.story_url === "string"
        ? item.story_url.trim()
        : "";

  if (!title || !url) return null;

  return {
    title,
    url,
    source: getNewsItemSource(url, item.author),
  };
}

function getNewsItemSource(url: string, author: unknown) {
  try {
    const hostname = new URL(url).hostname.replace(/^www\./, "");
    if (hostname) return hostname;
  } catch {}

  return typeof author === "string" && author.trim()
    ? author.trim()
    : "Hacker News";
}

export function isDiscordWebhookUrl(value: string) {
  try {
    const url = new URL(value);
    const isDiscordHost =
      url.hostname === "discord.com" || url.hostname === "discordapp.com";
    return (
      url.protocol === "https:" &&
      isDiscordHost &&
      url.pathname.startsWith("/api/webhooks/")
    );
  } catch {
    return false;
  }
}

function buildDiscordPayload({
  topic,
  items,
}: {
  topic: string;
  items: NewsItem[];
}) {
  const timestamp = new Date().toISOString();
  const description =
    items.length > 0
      ? items
          .map((item, index) => `${index + 1}. [${item.title}](${item.url})`)
          .join("\n")
      : "No matching stories were found during this run.";

  return {
    username: "Siteliyo Agent",
    embeds: [
      {
        title: `Latest ${topic} briefing`,
        description,
        color: 0x9dde58,
        footer: {
          text: "Generated by Siteliyo Agent Runner",
        },
        timestamp,
      },
    ],
  };
}

const tools: AgentTool[] = [
  {
    name: "manual_trigger",
    description: "Starts a manual agent run.",
    async execute(context) {
      return {
        tool: "manual_trigger",
        status: "completed",
        message: `Manual run started for ${context.plan.title}.`,
      };
    },
  },
  {
    name: "fetch_news",
    description: "Fetches recent public news stories for the agent topic.",
    async execute(context) {
      const topic = getTopicFromPrompt(context.prompt);
      const searchUrl = new URL("https://hn.algolia.com/api/v1/search_by_date");
      searchUrl.searchParams.set("query", topic);
      searchUrl.searchParams.set("tags", "story");
      searchUrl.searchParams.set("hitsPerPage", "12");

      const response = await fetch(searchUrl, {
        headers: {
          Accept: "application/json",
          "User-Agent": "Siteliyo-Agent-Runner/1.0",
        },
        signal: AbortSignal.timeout(12_000),
      });

      if (!response.ok) {
        throw new Error(`News source returned ${response.status}`);
      }

      const payload = (await response.json()) as { hits?: unknown[] };
      const seen = new Set<string>();
      const items: NewsItem[] = [];

      for (const hit of Array.isArray(payload.hits) ? payload.hits : []) {
        const item = normalizeNewsItem(hit);
        if (!item || seen.has(item.url)) continue;
        seen.add(item.url);
        items.push(item);
        if (items.length >= MAX_NEWS_ITEMS) break;
      }

      context.topic = topic;
      context.items = items;

      return {
        tool: "fetch_news",
        status: "completed",
        message: `Fetched ${items.length} stories for ${topic}.`,
        output: { topic, items },
      };
    },
  },
  {
    name: "format_discord_message",
    description: "Formats fetched items into a Discord embed payload.",
    async execute(context) {
      const topic = context.topic || getTopicFromPrompt(context.prompt);
      const items = context.items || [];
      const discordPayload = buildDiscordPayload({ topic, items });
      context.discordPayload = discordPayload;

      return {
        tool: "format_discord_message",
        status: "completed",
        message: "Formatted Discord embed payload.",
        output: { discordPayload },
      };
    },
  },
  {
    name: "discord_webhook",
    description:
      "Posts the formatted message to Discord when a webhook is provided.",
    async execute(context) {
      if (!context.webhookUrl) {
        return {
          tool: "discord_webhook",
          status: "skipped",
          message: "No Discord webhook URL provided; returning preview only.",
        };
      }

      if (!isDiscordWebhookUrl(context.webhookUrl)) {
        throw new Error("Only Discord webhook URLs are supported.");
      }

      const payload =
        context.discordPayload ||
        buildDiscordPayload({
          topic: context.topic || getTopicFromPrompt(context.prompt),
          items: context.items || [],
        });

      const deliveryResponse = await fetch(context.webhookUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
        signal: AbortSignal.timeout(12_000),
      });

      if (!deliveryResponse.ok) {
        const deliveryError = await deliveryResponse.text().catch(() => "");
        throw new Error(
          deliveryError || `Discord returned ${deliveryResponse.status}`,
        );
      }

      return {
        tool: "discord_webhook",
        status: "completed",
        message: "Posted the agent output to Discord.",
      };
    },
  },
];

export function getAgentTools() {
  return tools;
}

export async function executeAgentTools(input: {
  prompt: string;
  plan: AgentToolContext["plan"];
  webhookUrl?: string;
}) {
  const context: AgentToolContext = {
    prompt: input.prompt,
    plan: input.plan,
    webhookUrl: input.webhookUrl,
  };
  const steps: AgentToolResult[] = [];

  for (const tool of tools) {
    const result = await tool.execute(context);
    steps.push(result);
  }

  const delivered = steps.some(
    (step) => step.tool === "discord_webhook" && step.status === "completed",
  );

  return {
    status: delivered ? ("delivered" as const) : ("preview" as const),
    topic: context.topic,
    items: context.items || [],
    message: delivered
      ? "Agent run completed and posted to Discord."
      : "Agent run completed. Add a Discord webhook URL to deliver it.",
    discordPayload: context.discordPayload,
    steps,
  };
}
